#!/bin/sh
# You need to have an ssh link to vcloud!
./retrieve-jars.sh
if [ $? -ne 0 ]; then
  echo "Fehler: retrieve-jars.sh fehlgeschlagen!"
  exit 1
fi

benchexec/contrib/vcloud-benchmark.py benchmark.xml --vcloudMaster localhost --vcloudClientHeap 15000 --no-container --tool-directory java-smt/ --vcloudCPU 1230
